### ISSUE TITLE
Gate ctest call with flag

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-tensorflow#8]
We're currently running `ctest` everytime `setup.py` is invoked. We might want to gate this with some flag since not everyone every build needs to run these tests. Also, the tests add a dependency on `pytest` which we don't check for in `setup.py` (perhaps add as an extra?).

**Comment by twuebi** [comment]
Ran into this, build failed with missing dependency `pytest`

**Comment by sebpuetz** [comment]
Closed via #14 and #18
